FROM python:3.11-alpine

ENV PYTHONPATH /app

RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

RUN apk update \
    && apk upgrade \
    && apk add bash

WORKDIR /app

COPY ./compose/grpc/requirements-prod.txt /app

RUN pip install --upgrade pip \
    && pip install -r requirements-prod.txt

COPY ./src/server_grpc /app/server_grpc
COPY ./src/graph_fga /app/graph_fga

RUN find /app -type d -name .pytest_cache -exec rm -rf {} +

EXPOSE 9999

CMD ["python", "server_grpc/main.py"]
